In [1]:
import os, os.path
import numpy as np
import pandas as pd
import data_structures as ds
import setup_analysis as sa
import support_functions as sf
import importlib
import time
import warnings
import matplotlib.pyplot as plt
import model_afolu as ma
import model_circular_economy as mc
import model_ippu as mi
import model_socioeconomic as ms

importlib.reload(ds)
importlib.reload(sa)
importlib.reload(sf)
importlib.reload(ma)
importlib.reload(mc)
importlib.reload(mi)
importlib.reload(ms)

/Users/jsyme/Documents/Projects/git_jbus/lac_decarbonization/python/data_structures.py:721: UserWarning: Invalid subsector attribute 'key_varreqs_partial'. Valid return type values are:'pycategory_primary', 'abv_subsector', 'sector', 'abv_sector', 'key_varreqs_all'
  warnings.warn(f"Invalid subsector attribute '{return_type}'. Valid return type values are:{valid_rts}")
/Users/jsyme/Documents/Projects/git_jbus/lac_decarbonization/python/data_structures.py:721: UserWarning: Invalid subsector attribute 'key_varreqs_partial'. Valid return type values are:'pycategory_primary', 'abv_subsector', 'sector', 'abv_sector', 'key_varreqs_all'
  warnings.warn(f"Invalid subsector attribute '{return_type}'. Valid return type values are:{valid_rts}")

In [11]:
encode = "ISO-8859-1"
df_land_use = pd.read_csv("/Users/jsyme/Documents/Projects/FY21/SWCHE131_1000/Data/ingestion/FAOSTAT/Environment_LandUse_E_All_Data_(Normalized)/Environment_LandUse_E_All_Data_(Normalized).csv", encoding = encode)
df_land_cover = pd.read_csv("/Users/jsyme/Documents/Projects/FY21/SWCHE131_1000/Data/ingestion/FAOSTAT/Environment_LandCover_E_All_Data_(Normalized)/Environment_LandCover_E_All_Data_(Normalized).csv", encoding = encode)

# renaming for 
dict_item_rnm_lu = {
    6620: "croplands",
    6717: "forests_primary_incl_mangroves",
    6716: "forests_secondary_incl_mangroves",
    6655: "grasslands",
    6670: "all_other"
}

dict_item_rnm_lc = {
    6620: "croplands",
    6717: "forests_primary_incl_mangroves",
    6716: "forests_secondary_incl_mangroves",
    6655: "grasslands",
    6670: "all_other"
}

def prepare_data(
    df_lc: pd.DataFrame,
    df_lu: pd.DataFrame,
    country: str,
    year: int,
    element_keep: str = "Area",
    field_area: str = "Area",
    field_element: str = "Element",
    field_unit: str = "Unit",
    field_year: str = "Year",
    unit_keep: str = "1000 ha"
) -> pd.DataFrame:

    # land use component
    df_lu_merge = df_lu[
        df_lu[field_area].isin([country]) &
        df_lu[field_element].isin([element_keep]) &
        df_lu[field_unit].isin([unit_keep]) &
        df_lu[field_year].isin([year])
    ]
    
    df_lc_merge = df_lu[
        df_lc[field_area].isin([country]) &
        df_lc[field_unit].isin([unit_keep]) &
        df_lc[field_year].isin([year])
    ]

    return df_lc_merge, df_lu_merge

prepare_data(
    df_land_cover, df_land_use, "Brazil", 2019
)

<ipython-input-11-1de54bf98180>:43: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_lc_merge = df_lu[

(Empty DataFrame
 Columns: [Area Code, Area, Item Code, Item, Element Code, Element, Year Code, Year, Unit, Value, Flag]
 Index: [],
 Empty DataFrame
 Columns: [Area Code, Area, Item Code, Item, Element Code, Element, Year Code, Year, Unit, Value, Flag]
 Index: [])

In [6]:
df_land_cover

,Area Code,Area,Item Code,Item,Element Code,Element,Year Code,Year,Unit,Value,Flag
0,2,Afghanistan,6970,Artificial surfaces (including urban and assoc...,5007,Area from MODIS,2001,2001,1000 ha,88.1603,FC
1,2,Afghanistan,6970,Artificial surfaces (including urban and assoc...,5007,Area from MODIS,2002,2002,1000 ha,88.1818,FC
2,2,Afghanistan,6970,Artificial surfaces (including urban and assoc...,5007,Area from MODIS,2003,2003,1000 ha,88.2247,FC
3,2,Afghanistan,6970,Artificial surfaces (including urban and assoc...,5007,Area from MODIS,2004,2004,1000 ha,88.2462,FC
4,2,Afghanistan,6970,Artificial surfaces (including urban and assoc...,5007,Area from MODIS,2005,2005,1000 ha,88.3106,FC
...,...,...,...,...,...,...,...,...,...,...,...
173679,5817,Net Food Importing Developing Countries,6982,Coastal water bodies and intertidal areas,5008,Area from CCI_LC,2014,2014,1000 ha,NaN,A
173680,5817,Net Food Importing Developing Countries,6982,Coastal water bodies and intertidal areas,5008,Area from CCI_LC,2015,2015,1000 ha,NaN,A
173681,5817,Net Food Importing Developing Countries,6982,Coastal water bodies and intertidal areas,5008,Area from CCI_LC,2016,2016,1000 ha,NaN,A
173682,5817,Net Food Importing Developing Countries,6982,Coastal water bodies and intertidal areas,5008,Area from CCI_LC,2017,2017,1000 ha,NaN,A
173683,5817,Net Food Importing Developing Countries,6982,Coastal water bodies and intertidal areas,5008,Area from CCI_LC,2018,2018,1000 ha,NaN,A